"""
Anima 2B Style Explorer - Скрипт слияния данных
Объединяет оценки уникальности ИИ с фронтенд-базой данных, используя логику "Чистой Базы" (Pristine Base).
"""

import json
import os
import shutil
import time

# --- CONFIGURATION ---
ANALYSIS_FILE = "style_analysis.json"
DATA_JS = "app/data.js"
PRISTINE_BASE = "app/data.js.original"

def merge():
    # 1. Handle Pristine Base
    if not os.path.exists(PRISTINE_BASE):
        if os.path.exists(DATA_JS):
            print(f"[*] Creating Pristine Base: {PRISTINE_BASE}")
            shutil.copy2(DATA_JS, PRISTINE_BASE)
        else:
            print(f"❌ Error: {DATA_JS} not found. Cannot create base.")
            return
    
    # 2. Load the AI Scores
    if not os.path.exists(ANALYSIS_FILE):
        print(f"❌ Error: {ANALYSIS_FILE} not found. Run analysis first.")
        return
        
    print("[*] Loading AI Analysis Data...")
    with open(ANALYSIS_FILE, 'r') as f:
        analysis = json.load(f)

    # 3. Read from Pristine Base
    print(f"[*] Reading from Clean Base: {PRISTINE_BASE}")
    with open(PRISTINE_BASE, 'r', encoding='utf-8') as f:
        content = f.read()
        
    try:
        json_str = content.split('galleryData =', 1)[1].strip()
        if json_str.endswith(';'):
            json_str = json_str[:-1]
        gallery_data = json.loads(json_str)
    except Exception as e:
        print(f"❌ Error parsing pristine data: {e}")
        return

    # 4. Inject Scores
    print("[*] Merging Uniqueness scores...")
    merge_count = 0
    for item in gallery_data:
        artist_id = str(item['id'])
        if artist_id in analysis:
            item['uniqueness'] = analysis[artist_id].get('uniqueness', 0)
            merge_count += 1
        else:
            item['uniqueness'] = 0
            
        # Strip deprecated fields
        item.pop('tags', None)
        item.pop('cluster', None)

    # 5. Save to the active app file
    print(f"[*] Saving updated database to {DATA_JS}...")
    with open(DATA_JS, 'w', encoding='utf-8') as f:
        f.write(f"// Generated by AI Style Ensemble on {time.ctime()}\n")
        f.write("const galleryData = ")
        json.dump(gallery_data, f, indent=2, ensure_ascii=False)
        f.write(";")

    print(f"[✔] Successfully merged scores for {merge_count} artists!")

if __name__ == "__main__":
    merge()
